Repository brunomachadors/4inaline, pull requests merged in 2023-09, with the labels that each got.

#2 1 board
  .gitignore
  index.js
  package.json
  public/index.html
  readme.md
  src/components/Board/index.js
  src/components/Game/index.js
  src/components/Square/index.js
  src/components/Square/style.js
  src/index.css
  src/index.js
  yarn.lock
Labels: enhancement

#4 Game Rules
  src/components/Board/index.js
  src/components/Game/index.js
  src/components/Square/index.js
  src/components/Square/style.js
  src/index.css
  src/utils/checkWin.js
Labels: enhancement, style

#8 Debug mode added and style updated
  src/components/Board/index.js
  src/components/Board/style.js
  src/components/Buttons/style.js
  src/components/Game/index.js
  src/components/Game/style.js
  src/components/Player/style.js
  src/index.css
  src/index.js
  src/utils/playerColors.js
Labels: documentation, enhancement
